"""
Loads backend/data/catalog.json (generated by
backend/scripts/export_catalog.mjs from the frontend's plantsData.js)
and exposes helpers used to keep the LLM from recommending products
that don't actually exist in the store.
"""
import json
import os
from functools import lru_cache
from typing import Dict, List

_CATALOG_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "catalog.json")


@lru_cache(maxsize=1)
def _load() -> List[dict]:
    with open(_CATALOG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


@lru_cache(maxsize=1)
def name_to_department() -> Dict[str, str]:
    return {item["name"]: item["department"] for item in _load()}


@lru_cache(maxsize=1)
def catalog_names_list() -> List[str]:
    return sorted(name_to_department().keys())
